<a href="http://landlab.github.io"><img style="float: left" src="https://raw.githubusercontent.com/landlab/tutorials/master/landlab_header.png"></a>


# Introducing landlab EventLayers

---

For instructions on how to run an interactive iPython notebook, click here:
* https://github.com/landlab/tutorials/blob/master/README.md

For more Landlab tutorials, click here:
* https://github.com/landlab/landlab/wiki/Tutorials

---

In this tutorial we will:
* create and add layers to a landlab grid
* add properties to layers

A bit of magic so that we can plot within this notebook.

In [1]:
from __future__ import print_function
%matplotlib inline

## Accessing layers to a landlab grid

First we will begin by adding layers to a landlab `RasterModelGrid`. This is done through the `layers` attribute of landlab grids.

In [2]:
from landlab import RasterModelGrid
grid = RasterModelGrid((3, 5))
grid.layers

EventLayers(3)

Note that in landlab layer stacks are defined at cells and so the number of layer stacks is the same as the number of cells.

In [3]:
grid.layers.nstacks == grid.number_of_cells

True

Use the `nlayers` attribute to get the number of layers. Initially, there are no layers.

In [4]:
grid.layers.nlayers

0

Use the `dz` attribute to get a numpy array of the thickness of each layer in each stack. As there are no layers, `dz` will be empyty.

In [5]:
grid.layers.dz

array([], shape=(0, 3), dtype=float64)

## Adding layers

Let's add some layers to our grid. This is done through the `add` method function. Here we add a uniform layer to all of the stacks. `dz` now shows one layer.

In [6]:
grid.layers.add(1.)
grid.layers.dz

array([[ 1.,  1.,  1.]])

The layers don't have to be uniform. Let's add different amounts to each stack.

In [7]:
grid.layers.add([2., 3. , 4.])
grid.layers.dz

array([[ 1.,  1.,  1.],
       [ 2.,  3.,  4.]])

Now that our grid has a couple layers, we will have a look at two additional attributes of our layers: `thickness` to get the total thickness of all the layers, and `z` to get elevations (relative to the bottom of each stack) to the top of each layer.

In [8]:
grid.layers.thickness

array([ 3.,  4.,  5.])

In [9]:
grid.layers.z

array([[ 1.,  1.,  1.],
       [ 3.,  4.,  5.]])

## Eroding layers

Negative values passed to the `add` method will result in layers being eroded. Using a mixture of positive and negative values is find.

In [10]:
grid.layers.add([1., -.5, -4.5])
grid.layers.dz

array([[ 1. ,  1. ,  0.5],
       [ 2. ,  2.5,  0. ],
       [ 1. ,  0. ,  0. ]])

## Tracking layer properties

Thus far we only keep track of layer thicknesses. It is also possible to keep track of layer properties as well. This is done through keywords to the `add` method. The properties tracked are determined after the first layer is added and can't be added later. In this first example, we add a property called `age`.

In [11]:
grid = RasterModelGrid((3, 5))
grid.layers.add(1., age=1.)

Layer properties are access as with a regular Python `dict`.

In [12]:
grid.layers['age']

array([[ 1.,  1.,  1.]])

To get a list of the properties currently being tracked, use the `tracking` attribute.

In [13]:
grid.layers.tracking

['age']

As with layer thicknesses, values can be scalar or arrays.

In [14]:
grid.layers.add(3., age=[2, 3, 4])
grid.layers['age']

array([[ 1.,  1.,  1.],
       [ 2.,  3.,  4.]])

Eroding layers doesn't change layer properties, only layer thicknesses.

In [15]:
grid.layers.add([1., -3.5, 1.], age=5)
grid.layers['age']

array([[ 1.,  1.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  5.,  5.]])

Layer properties need not be scalars but could also be arrays. This could be useful, for example, if you wanted to track the fraction of different sediment types within a layer. Here we add an additional property, `f`, that tracks two values at each layer. 

In [16]:
grid = RasterModelGrid((3, 5))
grid.layers.add(1., age=1., f=(.2, .3))
grid.layers['f']

array([[[ 0.2,  0.3],
        [ 0.2,  0.3],
        [ 0.2,  0.3]]])

Again, you can add don't have to add a constant value for each stack.

In [17]:
grid.layers.add(2., age=2., f=[(.2, .3), (.1, .8), (.4, .5)])
grid.layers['f']

array([[[ 0.2,  0.3],
        [ 0.2,  0.3],
        [ 0.2,  0.3]],

       [[ 0.2,  0.3],
        [ 0.1,  0.8],
        [ 0.4,  0.5]]])

### Click here for more <a href="https://github.com/landlab/landlab/wiki/Tutorials">Landlab tutorials</a>